-- Entregas unicas por venda.
--
-- Principios de seguranca:
-- 1. Nenhum segredo e armazenado em texto puro. O backend grava somente
--    ciphertext AES-256-GCM, IV, auth tag e uma impressao HMAC.
-- 2. As tabelas nao possuem policies para anon/authenticated. Todo acesso passa
--    pelas rotas server-side, que usam service_role e validam propriedade.
-- 3. A alocacao ocorre no PostgreSQL, na mesma transacao que aprova o pedido,
--    usando FOR UPDATE SKIP LOCKED e restricoes UNIQUE.
-- 4. Uma entrega atribuida nunca volta ao estoque, inclusive apos estorno.

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS buyer_email_normalized TEXT;

UPDATE public.orders
SET buyer_email_normalized = LOWER(BTRIM(buyer_email))
WHERE buyer_email IS NOT NULL
  AND buyer_email_normalized IS DISTINCT FROM LOWER(BTRIM(buyer_email));

CREATE INDEX IF NOT EXISTS idx_orders_buyer_email_normalized_paid
    ON public.orders(buyer_email_normalized, created_at DESC)
    WHERE status = 'paid' AND buyer_email_normalized IS NOT NULL;

CREATE OR REPLACE FUNCTION public.goupay_normalize_order_buyer_email()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.buyer_email_normalized := NULLIF(LOWER(BTRIM(NEW.buyer_email)), '');
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS normalize_order_buyer_email ON public.orders;
CREATE TRIGGER normalize_order_buyer_email
BEFORE INSERT OR UPDATE OF buyer_email ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.goupay_normalize_order_buyer_email();

CREATE TABLE IF NOT EXISTS public.unique_delivery_settings (
    product_id UUID PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
    seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    enabled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_delivery_settings_enabled_at_check
        CHECK (NOT enabled OR enabled_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_settings_seller
    ON public.unique_delivery_settings(seller_id);

CREATE TABLE IF NOT EXISTS public.unique_delivery_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inventory_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    payload_ciphertext TEXT NOT NULL,
    payload_iv TEXT NOT NULL,
    payload_auth_tag TEXT NOT NULL,
    payload_fingerprint CHAR(64) NOT NULL,
    encryption_version SMALLINT NOT NULL DEFAULT 1 CHECK (encryption_version >= 1),
    status TEXT NOT NULL DEFAULT 'available'
        CHECK (status IN ('available', 'assigned', 'disabled')),
    assigned_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_delivery_item_assignment_state_check CHECK (
        (status = 'assigned' AND assigned_at IS NOT NULL)
        OR (status <> 'assigned')
    ),
    CONSTRAINT unique_delivery_item_fingerprint_unique
        UNIQUE (product_id, payload_fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_items_available
    ON public.unique_delivery_items(product_id, created_at, id)
    WHERE status = 'available';

CREATE INDEX IF NOT EXISTS idx_unique_delivery_items_seller
    ON public.unique_delivery_items(seller_id, product_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.unique_delivery_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id UUID NOT NULL REFERENCES public.unique_delivery_items(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL UNIQUE,
    metadata_ciphertext TEXT NOT NULL,
    metadata_iv TEXT NOT NULL,
    metadata_auth_tag TEXT NOT NULL,
    file_iv TEXT NOT NULL,
    file_auth_tag TEXT NOT NULL,
    encryption_version SMALLINT NOT NULL DEFAULT 1 CHECK (encryption_version >= 1),
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0 AND size_bytes <= 15728640),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_files_item
    ON public.unique_delivery_files(item_id, created_at);

CREATE TABLE IF NOT EXISTS public.unique_delivery_fulfillments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    item_id UUID REFERENCES public.unique_delivery_items(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'stock_unavailable'
        CHECK (status IN ('assigned', 'stock_unavailable')),
    assigned_at TIMESTAMPTZ,
    first_viewed_at TIMESTAMPTZ,
    last_viewed_at TIMESTAMPTZ,
    view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_delivery_fulfillment_order_product_unique
        UNIQUE (order_id, product_id),
    CONSTRAINT unique_delivery_fulfillment_item_unique
        UNIQUE (item_id),
    CONSTRAINT unique_delivery_fulfillment_state_check CHECK (
        (status = 'assigned' AND item_id IS NOT NULL AND assigned_at IS NOT NULL)
        OR (status = 'stock_unavailable' AND item_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_fulfillments_seller
    ON public.unique_delivery_fulfillments(seller_id, product_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_fulfillments_waiting
    ON public.unique_delivery_fulfillments(product_id, created_at)
    WHERE status = 'stock_unavailable';

-- Produtos adicionais comprados no mesmo pedido (carrinho ou order bump).
-- A tabela guarda apenas IDs, nunca o conteudo da entrega.
CREATE TABLE IF NOT EXISTS public.unique_delivery_order_products (
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_order_products_product
    ON public.unique_delivery_order_products(product_id, order_id);

CREATE TABLE IF NOT EXISTS public.unique_delivery_access_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fulfillment_id UUID NOT NULL
        REFERENCES public.unique_delivery_fulfillments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    file_id UUID REFERENCES public.unique_delivery_files(id) ON DELETE SET NULL,
    action TEXT NOT NULL CHECK (action IN ('view', 'download')),
    ip_hash CHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_unique_delivery_access_logs_fulfillment
    ON public.unique_delivery_access_logs(fulfillment_id, created_at DESC);

ALTER TABLE public.unique_delivery_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_items FORCE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_files FORCE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_fulfillments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_fulfillments FORCE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_order_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_order_products FORCE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_access_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unique_delivery_access_logs FORCE ROW LEVEL SECURITY;

-- Intencionalmente sem policies: anon/authenticated nao podem consultar,
-- inserir ou alterar ciphertext, metadados, estoque ou atribuicoes.

CREATE OR REPLACE FUNCTION public.goupay_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_unique_delivery_settings_updated_at
    ON public.unique_delivery_settings;
CREATE TRIGGER set_unique_delivery_settings_updated_at
BEFORE UPDATE ON public.unique_delivery_settings
FOR EACH ROW EXECUTE FUNCTION public.goupay_set_updated_at();

DROP TRIGGER IF EXISTS set_unique_delivery_items_updated_at
    ON public.unique_delivery_items;
CREATE TRIGGER set_unique_delivery_items_updated_at
BEFORE UPDATE ON public.unique_delivery_items
FOR EACH ROW EXECUTE FUNCTION public.goupay_set_updated_at();

DROP TRIGGER IF EXISTS set_unique_delivery_fulfillments_updated_at
    ON public.unique_delivery_fulfillments;
CREATE TRIGGER set_unique_delivery_fulfillments_updated_at
BEFORE UPDATE ON public.unique_delivery_fulfillments
FOR EACH ROW EXECUTE FUNCTION public.goupay_set_updated_at();

CREATE OR REPLACE FUNCTION public.assign_unique_delivery_for_product(
    p_order_id UUID,
    p_product_id UUID
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_order public.orders%ROWTYPE;
    v_enabled_at TIMESTAMPTZ;
    v_fulfillment_id UUID;
    v_fulfillment_status TEXT;
    v_existing_item_id UUID;
    v_item_id UUID;
BEGIN
    SELECT *
    INTO v_order
    FROM public.orders
    WHERE id = p_order_id;

    IF NOT FOUND
       OR v_order.status <> 'paid'
       OR p_product_id IS NULL
       OR v_order.seller_id IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT settings.enabled_at
    INTO v_enabled_at
    FROM public.unique_delivery_settings AS settings
    JOIN public.products AS product
      ON product.id = settings.product_id
     AND product.user_id = settings.seller_id
    WHERE settings.product_id = p_product_id
      AND settings.seller_id = v_order.seller_id
      AND (
          settings.enabled = TRUE
          OR EXISTS (
              SELECT 1
              FROM public.unique_delivery_order_products AS purchased_product
              WHERE purchased_product.order_id = v_order.id
                AND purchased_product.product_id = p_product_id
                AND purchased_product.seller_id = v_order.seller_id
          )
      );

    IF NOT FOUND
       OR v_enabled_at IS NULL
       OR v_order.created_at < v_enabled_at THEN
        RETURN NULL;
    END IF;

    INSERT INTO public.unique_delivery_fulfillments (
        order_id,
        product_id,
        seller_id,
        status
    )
    VALUES (
        v_order.id,
        p_product_id,
        v_order.seller_id,
        'stock_unavailable'
    )
    ON CONFLICT (order_id, product_id) DO NOTHING;

    SELECT id, status, item_id
    INTO v_fulfillment_id, v_fulfillment_status, v_existing_item_id
    FROM public.unique_delivery_fulfillments
    WHERE order_id = v_order.id
      AND product_id = p_product_id
    FOR UPDATE;

    IF v_fulfillment_status = 'assigned' THEN
        RETURN v_existing_item_id;
    END IF;

    SELECT item.id
    INTO v_item_id
    FROM public.unique_delivery_items AS item
    WHERE item.product_id = p_product_id
      AND item.seller_id = v_order.seller_id
      AND item.status = 'available'
    ORDER BY item.created_at, item.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1;

    IF v_item_id IS NULL THEN
        RETURN NULL;
    END IF;

    UPDATE public.unique_delivery_items
    SET status = 'assigned',
        assigned_at = NOW()
    WHERE id = v_item_id
      AND status = 'available';

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    UPDATE public.unique_delivery_fulfillments
    SET item_id = v_item_id,
        status = 'assigned',
        assigned_at = NOW()
    WHERE id = v_fulfillment_id
      AND status = 'stock_unavailable';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'unique delivery fulfillment changed during allocation';
    END IF;

    RETURN v_item_id;
END;
$$;

REVOKE ALL ON FUNCTION public.assign_unique_delivery_for_product(UUID, UUID)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assign_unique_delivery_for_product(UUID, UUID)
    TO service_role;

CREATE OR REPLACE FUNCTION public.goupay_assign_unique_deliveries_on_paid()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_additional_product_id UUID;
BEGIN
    IF NEW.status = 'paid'
       AND (
           TG_OP = 'INSERT'
           OR OLD.status IS DISTINCT FROM NEW.status
       ) THEN
        IF NEW.product_id IS NOT NULL THEN
            PERFORM public.assign_unique_delivery_for_product(NEW.id, NEW.product_id);
        END IF;

        IF to_regclass('public.order_bump_items') IS NOT NULL THEN
            FOR v_additional_product_id IN
                SELECT DISTINCT bump_product_id
                FROM public.order_bump_items
                WHERE order_id = NEW.id
                  AND bump_product_id IS NOT NULL
            LOOP
                PERFORM public.assign_unique_delivery_for_product(
                    NEW.id,
                    v_additional_product_id
                );
            END LOOP;
        END IF;

        FOR v_additional_product_id IN
            SELECT product_id
            FROM public.unique_delivery_order_products
            WHERE order_id = NEW.id
        LOOP
            PERFORM public.assign_unique_delivery_for_product(
                NEW.id,
                v_additional_product_id
            );
        END LOOP;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS assign_unique_deliveries_on_paid ON public.orders;
CREATE TRIGGER assign_unique_deliveries_on_paid
AFTER INSERT OR UPDATE OF status ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.goupay_assign_unique_deliveries_on_paid();

CREATE OR REPLACE FUNCTION public.goupay_assign_unique_delivery_on_bump_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_status TEXT;
BEGIN
    IF NEW.bump_product_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT status INTO v_status
    FROM public.orders
    WHERE id = NEW.order_id;

    IF v_status = 'paid' THEN
        PERFORM public.assign_unique_delivery_for_product(
            NEW.order_id,
            NEW.bump_product_id
        );
    END IF;

    RETURN NEW;
END;
$$;

DO $$
BEGIN
    IF to_regclass('public.order_bump_items') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS assign_unique_delivery_on_bump_insert
            ON public.order_bump_items';
        EXECUTE 'CREATE TRIGGER assign_unique_delivery_on_bump_insert
            AFTER INSERT ON public.order_bump_items
            FOR EACH ROW
            EXECUTE FUNCTION public.goupay_assign_unique_delivery_on_bump_insert()';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.goupay_assign_unique_delivery_on_order_product()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_status TEXT;
BEGIN
    SELECT status INTO v_status
    FROM public.orders
    WHERE id = NEW.order_id
      AND seller_id = NEW.seller_id;

    IF v_status = 'paid' THEN
        PERFORM public.assign_unique_delivery_for_product(
            NEW.order_id,
            NEW.product_id
        );
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS assign_unique_delivery_on_order_product
    ON public.unique_delivery_order_products;
CREATE TRIGGER assign_unique_delivery_on_order_product
AFTER INSERT ON public.unique_delivery_order_products
FOR EACH ROW
EXECUTE FUNCTION public.goupay_assign_unique_delivery_on_order_product();

CREATE OR REPLACE FUNCTION public.goupay_backfill_waiting_unique_delivery()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_order_id UUID;
BEGIN
    IF NEW.status <> 'available' THEN
        RETURN NEW;
    END IF;

    SELECT fulfillment.order_id
    INTO v_order_id
    FROM public.unique_delivery_fulfillments AS fulfillment
    JOIN public.orders AS payment_order
      ON payment_order.id = fulfillment.order_id
     AND payment_order.status = 'paid'
    WHERE fulfillment.product_id = NEW.product_id
      AND fulfillment.seller_id = NEW.seller_id
      AND fulfillment.status = 'stock_unavailable'
    ORDER BY payment_order.created_at, fulfillment.created_at
    FOR UPDATE OF fulfillment SKIP LOCKED
    LIMIT 1;

    IF v_order_id IS NOT NULL THEN
        PERFORM public.assign_unique_delivery_for_product(
            v_order_id,
            NEW.product_id
        );
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS backfill_waiting_unique_delivery
    ON public.unique_delivery_items;
CREATE TRIGGER backfill_waiting_unique_delivery
AFTER INSERT ON public.unique_delivery_items
FOR EACH ROW EXECUTE FUNCTION public.goupay_backfill_waiting_unique_delivery();

CREATE OR REPLACE FUNCTION public.record_unique_delivery_views(
    p_fulfillment_ids UUID[]
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.unique_delivery_fulfillments
    SET first_viewed_at = COALESCE(first_viewed_at, NOW()),
        last_viewed_at = NOW(),
        view_count = view_count + 1
    WHERE id = ANY(COALESCE(p_fulfillment_ids, ARRAY[]::UUID[]))
      AND status = 'assigned';
END;
$$;

REVOKE ALL ON FUNCTION public.record_unique_delivery_views(UUID[])
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_unique_delivery_views(UUID[])
    TO service_role;

-- Arquivos sao enviados ja cifrados e ficam em bucket privado. Nenhuma policy
-- de storage e criada; apenas service_role pode ler/gravar os objetos.
INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit
)
VALUES (
    'unique-deliveries',
    'unique-deliveries',
    FALSE,
    15728640
)
ON CONFLICT (id) DO UPDATE
SET public = FALSE,
    file_size_limit = EXCLUDED.file_size_limit;

NOTIFY pgrst, 'reload schema';
